// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: RackCommReader

#include "../ui.h"


// COMPONENT BlowerBIPanel

lv_obj_t *ui_BlowerBIPanel_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_BlowerBIPanel;
cui_BlowerBIPanel = lv_obj_create(comp_parent);
lv_obj_set_width( cui_BlowerBIPanel, lv_pct(50));
lv_obj_set_height( cui_BlowerBIPanel, lv_pct(50));
lv_obj_clear_flag( cui_BlowerBIPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(cui_BlowerBIPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_BlowerBIPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_BlowerBIPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_BlowerBIPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_DeviceLabel;
cui_DeviceLabel = lv_label_create(cui_BlowerBIPanel);
lv_obj_set_width( cui_DeviceLabel, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( cui_DeviceLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_DeviceLabel, LV_ALIGN_TOP_MID );
lv_label_set_text(cui_DeviceLabel,"Supply A");

lv_obj_t *cui_ChipIdPanel;
cui_ChipIdPanel = lv_obj_create(cui_BlowerBIPanel);
lv_obj_set_width( cui_ChipIdPanel, lv_pct(100));
lv_obj_set_height( cui_ChipIdPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_ChipIdPanel, 0 );
lv_obj_set_y( cui_ChipIdPanel, lv_pct(18) );
lv_obj_set_align( cui_ChipIdPanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( cui_ChipIdPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(cui_ChipIdPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_ChipIdPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_ChipIdPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_ChipIdPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_ChipIdPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_ChipIdPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_ChipIDTXTLable;
cui_ChipIDTXTLable = lv_label_create(cui_ChipIdPanel);
lv_obj_set_width( cui_ChipIDTXTLable, lv_pct(40));
lv_obj_set_height( cui_ChipIDTXTLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_ChipIDTXTLable, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_ChipIDTXTLable,"ChipID:");

lv_obj_t *cui_ChipIDValLable;
cui_ChipIDValLable = lv_label_create(cui_ChipIdPanel);
lv_obj_set_width( cui_ChipIDValLable, lv_pct(60));
lv_obj_set_height( cui_ChipIDValLable, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_ChipIDValLable, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_ChipIDValLable,"1234567891");

lv_obj_t *cui_OffsetPanel;
cui_OffsetPanel = lv_obj_create(cui_BlowerBIPanel);
lv_obj_set_width( cui_OffsetPanel, lv_pct(100));
lv_obj_set_height( cui_OffsetPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_OffsetPanel, 0 );
lv_obj_set_y( cui_OffsetPanel, lv_pct(36) );
lv_obj_set_align( cui_OffsetPanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( cui_OffsetPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(cui_OffsetPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_OffsetPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_OffsetPanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_OffsetPanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_OffsetPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_OffsetPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_OffseTXTLabel;
cui_OffseTXTLabel = lv_label_create(cui_OffsetPanel);
lv_obj_set_width( cui_OffseTXTLabel, lv_pct(40));
lv_obj_set_height( cui_OffseTXTLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_OffseTXTLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_OffseTXTLabel,"Offset:");

lv_obj_t *cui_OffsetValLabel;
cui_OffsetValLabel = lv_label_create(cui_OffsetPanel);
lv_obj_set_width( cui_OffsetValLabel, lv_pct(55));
lv_obj_set_height( cui_OffsetValLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_OffsetValLabel, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_OffsetValLabel,"-5");

lv_obj_t *cui_RangePanel;
cui_RangePanel = lv_obj_create(cui_BlowerBIPanel);
lv_obj_set_width( cui_RangePanel, lv_pct(100));
lv_obj_set_height( cui_RangePanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_RangePanel, 0 );
lv_obj_set_y( cui_RangePanel, lv_pct(54) );
lv_obj_set_align( cui_RangePanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( cui_RangePanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(cui_RangePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_RangePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_RangePanel, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_RangePanel, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_RangePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_RangePanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_RangeTXTLabel;
cui_RangeTXTLabel = lv_label_create(cui_RangePanel);
lv_obj_set_width( cui_RangeTXTLabel, lv_pct(40));
lv_obj_set_height( cui_RangeTXTLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_RangeTXTLabel, LV_ALIGN_LEFT_MID );
lv_label_set_text(cui_RangeTXTLabel,"Range:");

lv_obj_t *cui_OffsetValLabel1;
cui_OffsetValLabel1 = lv_label_create(cui_RangePanel);
lv_obj_set_width( cui_OffsetValLabel1, lv_pct(55));
lv_obj_set_height( cui_OffsetValLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_OffsetValLabel1, LV_ALIGN_RIGHT_MID );
lv_label_set_text(cui_OffsetValLabel1,"3");

lv_obj_t *cui_StatisPanel;
cui_StatisPanel = lv_obj_create(cui_BlowerBIPanel);
lv_obj_set_width( cui_StatisPanel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_StatisPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( cui_StatisPanel, 0 );
lv_obj_set_y( cui_StatisPanel, lv_pct(78) );
lv_obj_set_align( cui_StatisPanel, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( cui_StatisPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(cui_StatisPanel, lv_color_hex(0xD7D6D6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_StatisPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(cui_StatisPanel, lv_color_hex(0x020366), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(cui_StatisPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_StatisPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_StatisPanel, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_StatisPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_StatisPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(cui_StatisPanel, lv_color_hex(0xC5C5C5), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_StatisPanel, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

lv_obj_t *cui_StatusTXTLabel;
cui_StatusTXTLabel = lv_label_create(cui_StatisPanel);
lv_obj_set_width( cui_StatusTXTLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_StatusTXTLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_StatusTXTLabel, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(cui_StatusTXTLabel,"Status");
lv_obj_set_style_bg_color(cui_StatusTXTLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_StatusTXTLabel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_BLOWERBIPANEL_NUM);
children[UI_COMP_BLOWERBIPANEL_BLOWERBIPANEL] = cui_BlowerBIPanel;
children[UI_COMP_BLOWERBIPANEL_DEVICELABEL] = cui_DeviceLabel;
children[UI_COMP_BLOWERBIPANEL_CHIPIDPANEL] = cui_ChipIdPanel;
children[UI_COMP_BLOWERBIPANEL_CHIPIDPANEL_CHIPIDTXTLABLE] = cui_ChipIDTXTLable;
children[UI_COMP_BLOWERBIPANEL_CHIPIDPANEL_CHIPIDVALLABLE] = cui_ChipIDValLable;
children[UI_COMP_BLOWERBIPANEL_OFFSETPANEL] = cui_OffsetPanel;
children[UI_COMP_BLOWERBIPANEL_OFFSETPANEL_OFFSETXTLABEL] = cui_OffseTXTLabel;
children[UI_COMP_BLOWERBIPANEL_OFFSETPANEL_OFFSETVALLABEL] = cui_OffsetValLabel;
children[UI_COMP_BLOWERBIPANEL_RANGEPANEL] = cui_RangePanel;
children[UI_COMP_BLOWERBIPANEL_RANGEPANEL_RANGETXTLABEL] = cui_RangeTXTLabel;
children[UI_COMP_BLOWERBIPANEL_RANGEPANEL_OFFSETVALLABEL1] = cui_OffsetValLabel1;
children[UI_COMP_BLOWERBIPANEL_STATISPANEL] = cui_StatisPanel;
children[UI_COMP_BLOWERBIPANEL_STATISPANEL_STATUSTXTLABEL] = cui_StatusTXTLabel;
lv_obj_add_event_cb(cui_BlowerBIPanel, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_BlowerBIPanel, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_BlowerBIPanel_create_hook(cui_BlowerBIPanel);
return cui_BlowerBIPanel; 
}

