// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: RackCommReader

#ifndef _RACKCOMMREADER_UI_H
#define _RACKCOMMREADER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_BlowerChipIDPanel;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_chipidLabel;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_uuidLabel;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_offsetLabel;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_deviceLabel;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Header;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_Font_Awesome_Solid);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
